services:
  laravel:
    build: 
      context: ./laravel
    container_name: laravel_app
    volumes:
      - ./laravel:/var/www/html
    networks:
      - uwu_network
    environment:
      DB_HOST: mysql
      DB_DATABASE: laravel_db
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - uwu_network
    depends_on:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - uwu_network

  random_http:
    build:
      context: ./http-service
    container_name: random_http
    networks:
      - uwu_network
    ports:
      - "8080:8080"

networks:
  uwu_network:
    driver: bridge

volumes:
  mysql_data: {}